<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<ApplicationIcon>zipstudio.ico</ApplicationIcon>
	</PropertyGroup>

	<ItemGroup>
		<Reference Include="AssetStudio">
			<HintPath>..\lib\AssetStudio.dll</HintPath>
		</Reference>
		<Reference Include="System.Half">
			<HintPath>..\lib\System.Half.dll</HintPath>
		</Reference>
		<Reference Include="System.IO.Compression" />
		<Reference Include="System.IO.Compression.FileSystem" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\ZipStudio.Core\ZipStudio.Core.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="MessagePack" Version="2.5.301" />
		<PackageReference Include="Microsoft-WindowsAPICodePack-Shell" Version="1.1.3.3" />
	</ItemGroup>
</Project>